services:
  rapid-doc-server:
    container_name: rapid-doc-server
    image: hzkitty/rapid-doc:0.9.8
    ports:
      - "8888:8888"
    environment:
      - TZ=${TIMEZONE:-UTC}
      #- PADDLEOCRVL_VERSION=v1.6
      #- PADDLEOCRVL_VL_REC_BACKEND=vllm-server
      #- PADDLEOCRVL_VL_VL_REC_SERVER_URL=http://localhost:8118/v1
    restart: always
